services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4050


  backend:
    build: ./backend
    platform: linux/arm64/v8
    volumes:
      - ./backend/app/input:/app/input
      - ./backend/app/output:/app/output
      - ./backend/app/model:/app/model
    environment:
      - MIDI_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - MODEL_PATH=/app/model/melody_generator_lstm_v2.h5
    ports:
      - "4050:4050"



  model-trainer:
    build: ./model-trainer
    volumes:
      - ./backend/app/input:/app/input
      - ./backend/app/model:/app/model
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/model
    platform: linux/arm64/v8
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    stdin_open: true  
    tty: true    

volumes:
  input:
  output:
  model: